version: "3.8"

networks:
  echall-network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0.39
    container_name: echall-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
      - TZ=Asia/Seoul
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    networks:
      - echall-network

  redis:
    image: redis:latest
    container_name: echall-redis
    ports:
      - "6379:6379"
    networks:
      - echall-network

  mongo:
    image: mongo:latest
    container_name: echall-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: [ "--bind_ip", "0.0.0.0" ]
    volumes:
      - ./mongodb:/data/db
    networks:
      - echall-network

  springbootapp:
    build: .
    container_name: echall-springboot
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://echall-mysql:3306/${LOCAL_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_ROOT_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
      - SPRING_REDIS_HOST=echall-redis
      - SPRING_REDIS_PORT=6379
      - SPRING_MONGO_URI=mongodb://echall-mongo:27017/${MONGO_DATABASE}
    depends_on:
      - mysql
      - redis
      - mongo
    networks:
      - echall-network
